#!/bin/bash

PLUGIN_NAME=$1

MANIFEST=nagios.pp
CONFIG_DIR=/etc/nagios3/conf.d
PREFIX_FILENAMES=lma_
EXTENSION_FILENAMES=.cfg
PUPPET=$(which puppet)
PLUGIN_PUPPET_DIR=$(ls -d /etc/fuel/plugins/"$PLUGIN_NAME"*/puppet)
LAST_CHECK=/var/cache/lma_last_nodes_yaml.md5sum
LAST_CHECK_DELETED=/var/cache/lma_last_deleted_nodes_yaml.md5sum
CURRENT_CHECK=/var/cache/lma_current_nodes_yaml.md5sum
CURRENT_CHECK_DELETED=/var/cache/lma_current_deleted_nodes_yaml.md5sum
ASTUTE=/etc/hiera/astute.yaml
DELETED=/etc/hiera/deleted_nodes.yaml

if [[ -z "$PLUGIN_NAME" ]]; then
  cat << EOT
  Usage: $0 <PLUGIN_NAME>

  If $ASTUTE or $DELETED have changed since the last run, re-apply nagios manifest.
  Before puppet apply, the script removes the StackLight nagios configuration files.
EOT
  exit 1
fi

if [[ ! -f "$ASTUTE"  || ! -f "$DELETED" ]]; then
    echo "missing one or both files $ASTUTE and/or $DELETED !"
    exit 1
fi

if [[ ! -f $LAST_CHECK || ! -f $DELETED ]]; then
    # First run
    md5sum $ASTUTE 2>/dev/null > $LAST_CHECK
    md5sum $DELETED 2>/dev/null > $LAST_CHECK_DELETED
    exit 0
fi

md5sum $ASTUTE > $CURRENT_CHECK
md5sum $DELETED > $CURRENT_CHECK_DELETED

md5sum --status -c $LAST_CHECK
result_astute=$?
md5sum --status -c $LAST_CHECK_DELETED
result_deleted=$?

if [[ $result_astute -ne 0 || $result_deleted -ne 0 ]]; then
  if [ -d "$CONFIG_DIR" ]; then
    rm -f "$CONFIG_DIR"/"$PREFIX_FILENAMES"*"$EXTENSION_FILENAMES"
  fi
  set -e
  $PUPPET apply --modulepath="$PLUGIN_PUPPET_DIR/modules/:/etc/puppet/modules" "$PLUGIN_PUPPET_DIR/manifests/$MANIFEST"
  set +e

  md5sum --status  -c $LAST_CHECK
  result_astute=$?
  md5sum --status  -c $LAST_CHECK_DELETED
  result_deleted=$?
  if [[ $result_astute -ne 0 || $result_deleted -ne 0 ]]; then
    # OK, the hiera data hasn't been modified during the puppet run
    md5sum $ASTUTE > $LAST_CHECK
    md5sum $DELETED > $LAST_CHECK_DELETED
  fi
fi
