#!/bin/bash
set -eux

. "$(dirname "$(readlink -f "$0")")"/functions.sh

HTPASSWD_TARBALL_URL="https://forgeapi.puppetlabs.com/v3/files/leinaddm-htpasswd-0.0.3.tar.gz"
APACHE_TARBALL_URL="https://forgeapi.puppetlabs.com/v3/files/puppetlabs-apache-1.4.0.tar.gz"
CONCAT_TARBALL_URL="https://forgeapi.puppetlabs.com/v3/files/puppetlabs-concat-1.2.3.tar.gz"
STDLIB_TARBALL_URL="https://forgeapi.puppetlabs.com/v3/files/puppetlabs-stdlib-4.7.0.tar.gz"
FIREWALL_TARBALL_URL="https://forgeapi.puppetlabs.com/v3/files/puppetlabs-firewall-1.7.0.tar.gz"

download_packages \
    http://mirrors.kernel.org/ubuntu/pool/main/t/talloc/libtalloc2_2.1.0-1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/t/tevent/libtevent0_0.9.19-1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/l/ldb/libldb1_1.1.16-1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/n/ntdb/libntdb1_1.0-2ubuntu1_amd64.deb\
    http://security.ubuntu.com/ubuntu/pool/main/s/samba/libwbclient0_4.1.6+dfsg-1ubuntu2.14.04.13_amd64.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/l/ldb/python-ldb_1.1.16-1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/t/talloc/python-talloc_2.1.0-1_amd64.deb\
    http://security.ubuntu.com/ubuntu/pool/main/s/samba/samba-common-bin_4.1.6+dfsg-1ubuntu2.14.04.13_amd64.deb \
    http://security.ubuntu.com/ubuntu/pool/main/s/samba/samba-libs_4.1.6+dfsg-1ubuntu2.14.04.13_amd64.deb \
    http://security.ubuntu.com/ubuntu/pool/main/s/samba/libsmbclient_4.1.6+dfsg-1ubuntu2.14.04.13_amd64.deb \
    http://security.ubuntu.com/ubuntu/pool/main/s/samba/smbclient_4.1.6+dfsg-1ubuntu2.14.04.13_amd64.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/n/nagios-plugins/nagios-plugins-common_1.5-3ubuntu1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/n/nagios-plugins/nagios-plugins-basic_1.5-3ubuntu1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/a/apache2/apache2-utils_2.4.7-1ubuntu4.5_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/b/bsd-mailx/bsd-mailx_8.1.2-0.20131005cvs-1ubuntu0.14.04.1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/libn/libnet-snmp-perl/libnet-snmp-perl_6.0.1-2_all.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/n/nagios-plugins/nagios-plugins-standard_1.5-3ubuntu1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/n/nagios-plugins/nagios-plugins_1.5-3ubuntu1_all.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/n/nagios-images/nagios-images_0.8_all.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/n/nagios3/nagios3-common_3.5.1-1ubuntu1_all.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/n/nagios3/nagios3-cgi_3.5.1-1ubuntu1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/n/nagios3/nagios3-core_3.5.1-1ubuntu1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/n/nagios3/nagios3_3.5.1-1ubuntu1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/n/ntdb/python-ntdb_1.0-2ubuntu1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/t/tdb/python-tdb_1.2.12-1_amd64.deb\
    http://security.ubuntu.com/ubuntu/pool/main/s/samba/python-samba_4.1.6+dfsg-1ubuntu2.14.04.13_amd64.deb \
    http://mirrors.kernel.org/ubuntu/pool/main/w/whois/whois_5.1.1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/universe/h/heirloom-mailx/heirloom-mailx_12.5-4_amd64.deb


download_puppet_module "htpasswd" "${HTPASSWD_TARBALL_URL}"
download_puppet_module "apache" "${APACHE_TARBALL_URL}"
download_puppet_module "concat" "${CONCAT_TARBALL_URL}"
download_puppet_module "stdlib" "${STDLIB_TARBALL_URL}"
download_puppet_module "firewall" "${FIREWALL_TARBALL_URL}"
