#!/bin/bash
set -eux
ROOT="$(dirname "$(readlink -f "$0")")"
MODULES_DIR="${ROOT}"/deployment_scripts/puppet/modules
RPM_REPO="${ROOT}"/repositories/centos/
DEB_REPO="${ROOT}"/repositories/ubuntu/
HTPASSWD_TARBALL_URL="https://forgeapi.puppetlabs.com/v3/files/leinaddm-htpasswd-0.0.3.tar.gz"
FUEL_LIB_VERSION="6.0"
FUEL_LIB_TARBALL_URL="https://github.com/stackforge/fuel-library/archive/${FUEL_LIB_VERSION}.tar.gz"


function download_packages {
    while [ $# -gt 0 ]; do
        FILENAME=$(basename "$1")
        EXT=${FILENAME##*.}
        case ${EXT} in
            deb) REPO=$DEB_REPO;;
            rpm) REPO=$RPM_REPO;;
        esac

        rm -f "$REPO"/"$FILENAME"
        wget -qO - "$1" > "$REPO"/"$FILENAME"
        shift
    done
}

download_packages \
    http://mirrors.kernel.org/ubuntu/pool/main/t/talloc/libtalloc2_2.1.0-1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/t/tevent/libtevent0_0.9.19-1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/l/ldb/libldb1_1.1.16-1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/n/ntdb/libntdb1_1.0-2ubuntu1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/s/samba/libwbclient0_4.1.6+dfsg-1ubuntu2.14.04.7_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/l/ldb/python-ldb_1.1.16-1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/t/talloc/python-talloc_2.1.0-1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/s/samba/samba-common-bin_4.1.6+dfsg-1ubuntu2.14.04.7_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/s/samba/samba-libs_4.1.6+dfsg-1ubuntu2.14.04.7_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/s/samba/libsmbclient_4.1.6+dfsg-1ubuntu2.14.04.7_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/s/samba/smbclient_4.1.6+dfsg-1ubuntu2.14.04.7_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/n/nagios-plugins/nagios-plugins-common_1.5-3ubuntu1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/n/nagios-plugins/nagios-plugins-basic_1.5-3ubuntu1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/a/apache2/apache2-utils_2.4.7-1ubuntu4.4_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/b/bsd-mailx/bsd-mailx_8.1.2-0.20131005cvs-1ubuntu0.14.04.1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/libn/libnet-snmp-perl/libnet-snmp-perl_6.0.1-2_all.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/n/nagios-plugins/nagios-plugins-standard_1.5-3ubuntu1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/n/nagios-plugins/nagios-plugins_1.5-3ubuntu1_all.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/n/nagios-images/nagios-images_0.8_all.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/n/nagios3/nagios3-common_3.5.1-1ubuntu1_all.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/n/nagios3/nagios3-cgi_3.5.1-1ubuntu1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/n/nagios3/nagios3-core_3.5.1-1ubuntu1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/n/nagios3/nagios3_3.5.1-1ubuntu1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/n/ntdb/python-ntdb_1.0-2ubuntu1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/t/tdb/python-tdb_1.2.12-1_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/s/samba/python-samba_4.1.6+dfsg-1ubuntu2.14.04.7_amd64.deb\
    http://mirrors.kernel.org/ubuntu/pool/main/w/whois/whois_5.1.1_amd64.deb


rm -rf "${MODULES_DIR:?}"/{openstack,stdlib,htpasswd}
mkdir -p "${MODULES_DIR}"/{openstack,stdlib,htpasswd}

wget -qO- "${FUEL_LIB_TARBALL_URL}" | \
    tar -C "${MODULES_DIR}" --strip-components=3 -zxvf - \
    fuel-library-${FUEL_LIB_VERSION}/deployment/puppet/{openstack,stdlib}

wget -qO- "${HTPASSWD_TARBALL_URL}" | tar -C "${MODULES_DIR}/htpasswd" --strip-components=1 -xz
